In [1]:
import numpy as np

In [2]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

In [3]:
UE = E + [(j, i) for (i, j) in E]

In [4]:
size = len(V)

adjacency_matrix = np.zeros(shape=(size, size))

for i, j in E:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [5]:
size = len(V)

adjacency_matrix = np.zeros(shape=(size, size))

for i, j in UE:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [6]:
adjacency_list = {i: [] for i in V}

for i, j in E:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}

In [7]:
adjacency_list = {i: [] for i in V}

for i, j in UE:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4, 0], 2: [4, 3, 0], 3: [4, 1, 2], 4: [1, 2, 3]}

In [8]:
class Queue:
  def __init__(self):
    self.queue = []

  def isEmpty(self):
    return len(self.queue) == 0

  def enqueue(self, value):
    self.queue.append(value)

  def dequeue(self):
    value = None
    if not self.isEmpty():
      value = self.queue[0]
      self.queue = self.queue[1:]

    return value

  def __str__(self):
    return str(self.queue)


q = Queue()

q.enqueue(10)
q.enqueue(20)
q.enqueue(30)

print(q.dequeue())
print(q.dequeue())

q.enqueue(40)

print(q)

10
20
[30, 40]


In [9]:
def bfs_adjacency_list(adjacency_list, start_vertex):
  visited = {i: False for i in adjacency_list.keys()}

  q = Queue()

  visited[start_vertex] = True
  q.enqueue(start_vertex)

  while not q.isEmpty():
    curr_vertex = q.dequeue()
    for adj_vertex in adjacency_list[curr_vertex]:
      if not visited[adj_vertex]:
        visited[adj_vertex] = True
        q.enqueue(adj_vertex)

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_adjacency_list(adjacency_list=adjacency_list, start_vertex=0)

{0: True, 1: True, 2: True, 3: True, 4: True}

In [10]:
def neighbors(adjacency_matrix, vertex):
  return [i for i in range(len(adjacency_matrix[vertex])) if adjacency_matrix[vertex][i] == 1]


def bfs_adjacency_matrix(adjacency_matrix, start_vertex):
  visited = {i: False for i in range(len(adjacency_matrix[0]))}

  q = Queue()

  visited[start_vertex] = True
  q.enqueue(start_vertex)

  while not q.isEmpty():
    curr_vertex = q.dequeue()
    for adj_vertex in neighbors(adjacency_matrix=adjacency_matrix, vertex=curr_vertex):
      if not visited[adj_vertex]:
        visited[adj_vertex] = True
        q.enqueue(adj_vertex)

  return visited


V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for i, j in E:
  adjacency_matrix[i, j] = 1

bfs_adjacency_matrix(adjacency_matrix=adjacency_matrix, start_vertex=0)

{0: True, 1: True, 2: True, 3: True, 4: True}

In [11]:
def bfs_adjacency_list(adjacency_list, start_vertex):
  levels = {i: -1 for i in adjacency_list.keys()}
  parents = {i: -1 for i in adjacency_list.keys()}

  q = Queue()

  levels[start_vertex] = 0
  q.enqueue(start_vertex)

  while not q.isEmpty():
    curr_vertex = q.dequeue()
    for adj_vertex in adjacency_list[curr_vertex]:
      if levels[adj_vertex] == -1:
        levels[adj_vertex] = levels[curr_vertex] + 1
        parents[adj_vertex] = curr_vertex
        q.enqueue(adj_vertex)

  return levels, parents


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
print(bfs_adjacency_list(adjacency_list=adjacency_list, start_vertex=0))
print(({0: 0, 1: 1, 2: 1, 3: 2, 4: 2}, {0: -1, 1: 0, 2: 0, 3: 1, 4: 1}))

({0: 0, 1: 1, 2: 1, 3: 2, 4: 2}, {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})
({0: 0, 1: 1, 2: 1, 3: 2, 4: 2}, {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})


In [12]:
class Stack:
  def __init__(self):
    self.stack = []

  def isEmpty(self):
    return len(self.stack) == 0

  def push(self, value):
    self.stack.append(value)

  def pop(self):
    value = None
    if not self.isEmpty():
      value = self.stack.pop()

    return value

  def __str__(self):
    return str(self.stack)


s = Stack()

s.push(10)
s.push(20)
s.push(30)

print(s.pop())
print(s.pop())

s.push(40)

print(s)

30
20
[10, 40]


In [13]:
def dfs_adjacency_list(adjacency_list, start_vertex):
  visited = {i: False for i in adjacency_list.keys()}

  s = Stack()
  s.push(start_vertex)

  while not s.isEmpty():
    curr_vertex = s.pop()
    if not visited[curr_vertex]:
      visited[curr_vertex] = True
      for adj_vertex in adjacency_list[curr_vertex]:
        s.push(adj_vertex)

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
dfs_adjacency_list(adjacency_list=adjacency_list, start_vertex=0)

{0: True, 1: True, 2: True, 3: True, 4: True}

In [14]:
def dfs_adjacency_list_recursive(adjacency_list, vertex, visited=None):
  if visited == None:
    visited = {i: False for i in adjacency_list.keys()}

  if not visited[vertex]:
    visited[vertex] = True
    for adj_vertex in adjacency_list[vertex]:
      if not visited[adj_vertex]:
        dfs_adjacency_list_recursive(
            adjacency_list=adjacency_list, vertex=adj_vertex, visited=visited)

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
dfs_adjacency_list_recursive(adjacency_list=adjacency_list, vertex=0)

{0: True, 1: True, 2: True, 3: True, 4: True}

In [43]:
a = np.array([
    [1, 2, 3], [4, 5, 6]
])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.zeros(shape=(2, 5))
np.ones(shape=(2, 2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [53]:
np.arange(20, 30)
np.arange(20, 30, 2)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

array([20, 22, 24, 26, 28])

In [60]:
np.linspace(20, 30)
np.linspace(20, 30, 2)
np.linspace(20, 30, 5)
np.linspace(20, 30, 10)

array([20.        , 20.20408163, 20.40816327, 20.6122449 , 20.81632653,
       21.02040816, 21.2244898 , 21.42857143, 21.63265306, 21.83673469,
       22.04081633, 22.24489796, 22.44897959, 22.65306122, 22.85714286,
       23.06122449, 23.26530612, 23.46938776, 23.67346939, 23.87755102,
       24.08163265, 24.28571429, 24.48979592, 24.69387755, 24.89795918,
       25.10204082, 25.30612245, 25.51020408, 25.71428571, 25.91836735,
       26.12244898, 26.32653061, 26.53061224, 26.73469388, 26.93877551,
       27.14285714, 27.34693878, 27.55102041, 27.75510204, 27.95918367,
       28.16326531, 28.36734694, 28.57142857, 28.7755102 , 28.97959184,
       29.18367347, 29.3877551 , 29.59183673, 29.79591837, 30.        ])

array([20., 30.])

array([20. , 22.5, 25. , 27.5, 30. ])

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [77]:
np.full(shape=(2, 2), fill_value=10)
np.eye(4)

array([[10, 10],
       [10, 10]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [132]:
# Return random floats in the half-open interval [0.0, 1.0)

np.random.random()
np.random.random(5)
np.random.random(size=(2, 5))

0.3698388352919981

array([0.57568608, 0.85321703, 0.7554479 , 0.45172895, 0.80542935])

array([[0.41843622, 0.21771368, 0.13898973, 0.38076006, 0.61642414],
       [0.43645442, 0.95579964, 0.34070873, 0.87948456, 0.10975862]])

In [135]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

np.random.rand()
np.random.rand(5)
np.random.rand(2, 5)

0.8385162012999259

array([0.30476513, 0.2389067 , 0.30677314, 0.30447877, 0.59372738])

array([[0.41139892, 0.46329685, 0.78441162, 0.83205826, 0.35867641],
       [0.38780589, 0.65356784, 0.82165667, 0.3561205 , 0.84312707]])

In [186]:
# Return random integers from low (inclusive) to high (exclusive).

# TypeError: randint() takes at least 1 positional argument (0 given)
# np.random.randint()

np.random.randint(5)
np.random.randint(10, 20)
np.random.randint(10, 20, size=(2, 2))

4

12

array([[11, 18],
       [13, 17]])

In [184]:
# Return a sample (or samples) from the "standard normal" distribution.

np.random.randn()
np.random.randn(5)
np.random.randn(2, 5)

-0.7362032919259335

array([-0.28863734, -0.52594541,  2.49380833,  0.56920386, -0.7791087 ])

array([[-0.1817415 ,  1.41369028, -1.28521944, -0.87832458, -1.14765644],
       [-2.3185687 ,  0.17123927,  0.81572847,  0.1160143 ,  0.00413228]])

In [185]:
# np.info(np.random)

In [348]:
np.random.seed(2)

a = np.array([
    np.random.randint(10, size=5),
    np.random.randint(10, size=5),
    np.random.randint(10, size=5),
])

# a[0::2, ::2]

a[[0, 1], [0]]

a
# a[::-1, ::-1]

a.ravel()

array([8, 7])

array([[8, 8, 6, 2, 8],
       [7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6]])

array([8, 8, 6, 2, 8, 7, 2, 1, 5, 4, 4, 5, 7, 3, 6])

In [271]:
a = [1, 2, 3]

a[::-1]

[3, 2, 1]

In [273]:
a = np.array([1, 2, 3])

a[::-1]

array([3, 2, 1])

In [309]:
np.random.seed(1)

a = np.random.randint(10, size=5)

a
a > 5
a[a > 5]

array([5, 8, 9, 5, 0])

array([False,  True,  True, False, False])

array([8, 9])

In [347]:
a = np.array([
    [1, 2, 3, 4], [5, 6, 7, 8]
])

a

# a.T
# a.reshape(4, 2)
a.ravel()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [344]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b), axis=0)

# AxisError: axis 1 is out of bounds for array of dimension 1
# np.concatenate((a, b), axis=1)

np.vstack((a, b))
np.hstack((a, b))

np.column_stack((a, b))
np.vstack((a, b)).T

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

array([[1, 4],
       [2, 5],
       [3, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])